org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.240
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT
mod_id=mcpaint
mod_name=McPaint-1.21.1
mod_license=GPL Version 3
mod_version=1.0.0
mod_group_id=ichttt.mods
mod_authors=ichttt,Renyigesai
mod_description=Paint your blocks the way you want them to be!The mod adds two items, a brush and a stamp. The brush can be crafted like a pickaxe but with wool instead of your pickaxe material at the top.Right-click any block with the brush and a editor will pop up where you can paint it!The resolution can be changed from 8x8 up to 128x128 for a single block.
